{
  "branches": ["main"],
  "repositoryUrl": "https://github.com/gagansingh894/jams-rs",
  "plugins": [
    ["@semantic-release/commit-analyzer", { "preset": "angular" }],
    ["@semantic-release/release-notes-generator", { "preset": "angular" }],
    ["@semantic-release/changelog", { "changelogFile": "CHANGELOG.md" }],
    ["@semantic-release/git", { "assets": ["CHANGELOG.md"] }],
    ["@semantic-release/github", { "assets": ["CHANGELOG.md"] }]
  ],
  "tagFormat": "${version}",
  "preset": "angular",
  "initialVersion": "0.0.0",
  "changelogFile": "CHANGELOG.md"
}
