{
  "branches": [
    "main"
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": [
          "CHANGELOG.md"
        ]
      }
    ],
    "@semantic-release/github"
  ],
  "tagFormat": "${version}",
  "preset": "angular",
  "release": {
    "verifyConditions": [
      "@semantic-release/changelog",
      "@semantic-release/git"
    ],
    "prepare": [
      "@semantic-release/changelog",
      {
        "path": "@semantic-release/git",
        "assets": [ "CHANGELOG.md" ],
      }
    ]
  },
  "changelogFile": "CHANGELOG.md"
}