{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", { "changelogFile": "CHANGELOG.md" }],
    ["@semantic-release/git", { "assets": ["CHANGELOG.md"] }],
    ["@semantic-release/github", { "assets": ["CHANGELOG.md"] }],
    ["@semantic-release/exec", {
      "prepareCmd": "cargo metadata --format-version=1 --no-deps --manifest-path=Cargo.toml | jq -r '.packages[0].version'",
      "publishCmd": "echo Skipping publish step"
    }]
  ],
  "changelogFile": "CHANGELOG.md"
}