version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:1.78
    resource_class: large
    environment:
      CARGO_TERM_COLOR: always
      LIGHTGBM_LIB_DIR: /usr/local/lib
      LIBTORCH: /usr/local/lib/libtorch
      LIBTORCH_INCLUDE: /usr/local/lib/libtorch
      LIBTORCH_LIB: /usr/local/lib/libtorch
      LD_LIBRARY_PATH: /usr/local/lib/libtorch/lib:/usr/local/lib

jobs:
  build:
    executor: rust-executor
    steps:
      - checkout

      - run:
          name: Setup Environment
          command: bash build/setup_environment_linux_x86_64.sh

      - run:
          name: Lint
          command: make lint

      - run:
          name: Run tests
          command: make test

      - run:
          name: Install cargo-llvm-cov
          command: cargo install cargo-llvm-cov

      - run:
          name: Generate code coverage
          command: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f lcov.info -F rust
          when: always

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              only: main
