# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jams.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njams.proto\x12\x07jams_v1\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\"\xa2\x01\n\x11GetModelsResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x30\n\x06models\x18\x02 \x03(\x0b\x32 .jams_v1.GetModelsResponse.Model\x1aL\n\x05Model\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tframework\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x14\n\x0clast_updated\x18\x04 \x01(\t\"%\n\x0f\x41\x64\x64ModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"(\n\x12UpdateModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"(\n\x12\x44\x65leteModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t2\x91\x03\n\x0bModelServer\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n\x07Predict\x12\x17.jams_v1.PredictRequest\x1a\x18.jams_v1.PredictResponse\x12?\n\tGetModels\x12\x16.google.protobuf.Empty\x1a\x1a.jams_v1.GetModelsResponse\x12<\n\x08\x41\x64\x64Model\x12\x18.jams_v1.AddModelRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x0bUpdateModel\x12\x1b.jams_v1.UpdateModelRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x0b\x44\x65leteModel\x12\x1b.jams_v1.DeleteModelRequest\x1a\x16.google.protobuf.EmptyB$\n\x04jamsB\tJAMSProtoZ\x11/pkg/pb/jams;jamsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jams_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\004jamsB\tJAMSProtoZ\021/pkg/pb/jams;jams'
  _globals['_PREDICTREQUEST']._serialized_start=52
  _globals['_PREDICTREQUEST']._serialized_end=103
  _globals['_PREDICTRESPONSE']._serialized_start=105
  _globals['_PREDICTRESPONSE']._serialized_end=138
  _globals['_GETMODELSRESPONSE']._serialized_start=141
  _globals['_GETMODELSRESPONSE']._serialized_end=303
  _globals['_GETMODELSRESPONSE_MODEL']._serialized_start=227
  _globals['_GETMODELSRESPONSE_MODEL']._serialized_end=303
  _globals['_ADDMODELREQUEST']._serialized_start=305
  _globals['_ADDMODELREQUEST']._serialized_end=342
  _globals['_UPDATEMODELREQUEST']._serialized_start=344
  _globals['_UPDATEMODELREQUEST']._serialized_end=384
  _globals['_DELETEMODELREQUEST']._serialized_start=386
  _globals['_DELETEMODELREQUEST']._serialized_end=426
  _globals['_MODELSERVER']._serialized_start=429
  _globals['_MODELSERVER']._serialized_end=830
# @@protoc_insertion_point(module_scope)
