[package]
name = "jams-proto"
version = "0.1.0"
edition = "2021"

[lib]
name = "jams_proto"
crate-type = ["lib"]


[dependencies]
tonic = "0.11"
tonic-reflection = "0.11.0"
prost = "0.12"
prost-types = "0.12"

[build-dependencies]
tonic-build = "0.11.0"