// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	http "github.com/gagansingh894/jams-rs/clients/go/jams/http"
	mock "github.com/stretchr/testify/mock"

	types "github.com/gagansingh894/jams-rs/clients/go/jams/types"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddModel provides a mock function with given fields: ctx, request
func (_m *Client) AddModel(ctx context.Context, request *http.AddModelRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AddModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.AddModelRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteModel provides a mock function with given fields: ctx, modelName
func (_m *Client) DeleteModel(ctx context.Context, modelName string) error {
	ret := _m.Called(ctx, modelName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, modelName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModels provides a mock function with given fields: ctx
func (_m *Client) GetModels(ctx context.Context) (*http.GetModelsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetModels")
	}

	var r0 *http.GetModelsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*http.GetModelsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *http.GetModelsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.GetModelsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *Client) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Predict provides a mock function with given fields: ctx, request
func (_m *Client) Predict(ctx context.Context, request *http.PredictRequest) (types.Prediction, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Predict")
	}

	var r0 types.Prediction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.PredictRequest) (types.Prediction, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.PredictRequest) types.Prediction); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Prediction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.PredictRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateModel provides a mock function with given fields: ctx, request
func (_m *Client) UpdateModel(ctx context.Context, request *http.UpdateModelRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.UpdateModelRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
