name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: rust:1.78
      options: --user root
      env:
        LIGHTGBM_LIB_DIR: /usr/local/lib
        LIBTORCH: /usr/local/lib/libtorch
        LIBTORCH_INCLUDE: /usr/local/lib/libtorch
        LIBTORCH_LIB: /usr/local/lib/libtorch
        LD_LIBRARY_PATH: /usr/local/lib/libtorch/lib:/usr/local/lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: bash build/setup_environment.sh

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test