name: J.A.M.S CI/CD Pipeline

# todo: run language specific cicd pipelines
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'clients/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'clients/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Lint, Test and Build Application
    runs-on: ubuntu-latest

    container:
      image: rust:1.78
      options: --user root
      env:
        LIGHTGBM_LIB_DIR: /usr/local/lib
        LIBTORCH: /usr/local/lib/libtorch
        LIBTORCH_INCLUDE: /usr/local/lib/libtorch
        LIBTORCH_LIB: /usr/local/lib/libtorch
        LD_LIBRARY_PATH: /usr/local/lib/libtorch/lib:/usr/local/lib
        PROTOC: /usr/bin/protoc
        USE_LOCALSTACK: true
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: eu-west-2
        LOCALSTACK_HOSTNAME: localstack
        USE_AZURITE: true
        STORAGE_ACCOUNT: devstoreaccount1
        # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage#well-known-storage-account-and-key
        STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }} # This is a dummy key but has a value which matches the form of actual key as per Azurite docs. Hence I have set it as GITHUB secrets.
        AZURITE_HOSTNAME: azurite

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566  # Edge port for all services
        env:
          SERVICES: s3
          DEBUG: 1
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: bash build/setup_environment_linux_x86_64.sh

      - name: Lint
        run: make lint

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run tests
        run: make nextest

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: build

    container:
      image: rust:1.78
      options: --user root
      env:
        LIGHTGBM_LIB_DIR: /usr/local/lib
        LIBTORCH: /usr/local/lib/libtorch
        LIBTORCH_INCLUDE: /usr/local/lib/libtorch
        LIBTORCH_LIB: /usr/local/lib/libtorch
        LD_LIBRARY_PATH: /usr/local/lib/libtorch/lib:/usr/local/lib
        PROTOC: /usr/bin/protoc
        USE_LOCALSTACK: true
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: eu-west-2
        LOCALSTACK_HOSTNAME: localstack
        USE_AZURITE: true
        STORAGE_ACCOUNT: devstoreaccount1
        # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage#well-known-storage-account-and-key
        STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }} # This is a dummy key but has a value which matches the form of actual key as per Azurite docs. Hence I have set it as GITHUB secrets.
        AZURITE_HOSTNAME: azurite

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566  # Edge port for all services
        env:
          SERVICES: s3
          DEBUG: 1
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: bash build/setup_environment_linux_x86_64.sh

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov nextest -p jams-core -p jams-serve --retries 2 --all-features --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  release:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jams:latest -f build/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jams:latest

      - name: Build Docker image for HTTP testing
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jams_http:latest -f build/Dockerfile_http .

      - name: Push Docker image - HTTP testing
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jams_http:latest

      - name: Build Docker image for gRPC testing
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jams_grpc:latest -f build/Dockerfile_grpc .

      - name: Push Docker image - gRPC testing
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jams_grpc:latest


  # New Job for ARM Release
  release-arm:
    name: Build and Publish Docker Image for ARM
    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for ARM
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jams:arm64 -f build/Dockerfile_arm64 .

      - name: Push Docker image for ARM
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jams:arm64