name: J.A.M.S Rust Client CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'clients/rust/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'clients/rust/**'

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest

    container:
      image: rust:1.78
      options: --user root
      env:
        PROTOC: /usr/bin/protoc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        run: |
          echo "Installing protoc..."
          apt-get update
          apt-get install -y protobuf-compiler

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Lint
        run: |
          cd clients/rust/jams-client
          make lint

      - name: Run tests
        run: |
          cd clients/rust/jams-client
          make nextest