name: J.A.M.S Builder Image CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'build/Dockerfile_builder'
      - '.github/workflows/jams_builder.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'build/Dockerfile_builder'
      - '.github/workflows/jams_builder.yml'

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jams_builder:latest -f build/Dockerfile_builder .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jams_builder:latest:latest
