name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
          bump_each_commit: true

    - uses: actions/checkout@v4
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose