name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: rust:1.78

    steps:
    # todo: fix this as it is not working
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
          bump_each_commit: true

    - name: Setup Environment
      uses: actions/checkout@v4
      run: .github/setup_environment.sh

    - name: Build
      run: make build
    - name: Run tests
      run: make test